# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6592fd4819722b249b2e8d8cd1615311"
name = "NotifyMe"
application_url = "https://notifyme-silbon.vercel.app"
embedded = false

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://notifyme-silbon.vercel.app/callback" ]
